steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker build \
        -t asia-northeast3-docker.pkg.dev/playground-yeoul-kim-b12d/kopring-demo/k8s:$(date +%Y-%m-%d)_$SHORT_SHA \
        '--network=cloudbuild' \
        .
images:
  - asia-northeast3-docker.pkg.dev/playground-yeoul-kim-b12d/kopring-demo/k8s

options:
  machineType: 'E2_HIGHCPU_8'

timeout: 1600s